---
name: Satel-server-deployment
description: Deploys server side of webapp 
inputs:
  app-name:
    description: Provide version type [major, minor, patch]
    required: true
  server-dir:
    description: Directory for server
    required: false  
  satel-docker-user:
    description: Username for satel docker registry
    required: false 
  satel-docker-pass:
    description: Password for satel docker registry 
    required: false 
  client-docker-user:
    description: Username for client docker registry
    required: false 
  client-docker-pass:
    description: Password for client docker registry 
    required: false      
  satel-registry:
    description: Satel registry address
    required: false  
  client-registry:
    description: Client registry address
    required: false   
  dockerfile:
    description: Dockerfile 
    required: false
    default: Dockerfile
  current-branch-name: 
    description: Provides current branch name 
    required: false    
  tag-name: 
    description: Provides current tag name 
    required: false  


runs:
  using: node16
  main: dist/index.js
